version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: bitnami/laravel:latest
    environment:
      - LARAVEL_DATABASE_TYPE=${DB_CONNECTION}
      - LARAVEL_DATABASE_HOST=${DB_HOST}
      - LARAVEL_DATABASE_PORT_NUMBER=${DB_PORT}
      - LARAVEL_DATABASE_NAME=${DB_DATABASE}
      - LARAVEL_DATABASE_USER=${DB_USERNAME}
      - LARAVEL_DATABASE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "
      composer install &&
      php artisan migrate &&
      php artisan serve --host=0.0.0.0 --port=8000
      "

volumes:
  mysql_data:
